### PR TITLE
Adding YAML Runner option to Tutorial section of QuickStart

### PR DESCRIPTION
**Pull request by CamrynCarter**
Waiting to test Event creation YAML. Need language on the 'operation' element of the CREATE_EVENT Yaml.

### CODE REVIEW

**Comment by CamrynCarter** [comment]
Ready for review. There is a spacing issue on import subject yaml in OBAC section, <subject-id-string> is correctly spaced in the markdown (line 491), but was too far indented on the web view.

**Comment by CamrynCarter** [comment]
Spacing issue resolved, using example subject id in yaml.

**Comment by leflambeur** [comment]
The language and the tone on this is perfect for me, one small(-ish 😛 ) change I would ask for:

I feel like the benefit of the tutorial is having the steps contiguous so it would be beneficial to have a kind of 'here's everything from each section stitched together' as a summary as opposed to only having each step individually in the YAML 

Could we add a summary section which has all the steps in one contiguous codeblock? To illustrate the key feature of the YAML runner being able to handle all of the steps in a row?

**Review by leflambeur — CHANGES_REQUESTED** [review]
See my earlier comment

**Comment by leflambeur** [comment]
Superseded 😃

**Pull request closed without merging**
